---
- name: Prepare RHEL playground
  hosts: all
  user: root

  tasks:

    - name: Subscribe to RHEL subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        auto_attach: true
    
    - name: Update every ansible.builtin.package
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: Install packages
      ansible.builtin.package:
        name:
          - ansible-core
          - cockpit
          - cockpit-machines
          - libvirt
          - podman
          - git
          - podman
          - tmux
        state: present

    - name: Enable and run cockpit and libvirt
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - cockpit.socket
        - libvirtd

    - name: Allow 8443 port on firewalld
      ansible.posix.firewalld:
        port: 8443/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Add a new user called yp and assign root rights to new user
      ansible.builtin.user:
        name: yp
        state: present
        groups:
          - wheel
        append: true

