# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="spaceship"

plugins=(git 
    kubectl 
    zsh-autosuggestions
    zsh-history-substring-search
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Example aliases
alias zshconfig="code ~/.zshrc"
alias zshsource="source ~/.zshrc"
alias dwn="yt-dlp -o \"%(playlist)s/%(title)s.%(ext)s\" --parse-metadata \"playlist:%(album)s\" --parse-metadata \"playlist:%(artist)s\" --parse-metadata \"%(playlist_index)s:%(track_number)s\"  --embed-metadata --paths /Users/yp/Documents/music/albums --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0"

# Spaceship
SPACESHIP_PROMPT_ORDER=(
    time
    user          # Username section
    host          # Hostname section
    dir           # Current directory section
    git           # Git section (git_branch + git_status)
    hg            # Mercurial section (hg_branch  + hg_status)
    exec_time     # Execution time
    line_sep      # Line break
    jobs          # Background jobs indicator
    exit_code     # Exit code section
    char          # Prompt character
)

SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_PROMPT_SUFFIXES_SHOW=true
SPACESHIP_PROMPT_DEFAULT_PREFIX="via "
SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "
SPACESHIP_CHAR_SUFFIX=" "

eval "$(mcfly init zsh)"